//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KioskClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сеансов нет.
        /// </summary>
        internal static string NoShowtimesText {
            get {
                return ResourceManager.GetString("NoShowtimesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрано {0} места.
        /// </summary>
        internal static string SeatsTextCouple {
            get {
                return ResourceManager.GetString("SeatsTextCouple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрано {0} мест.
        /// </summary>
        internal static string SeatsTextMany {
            get {
                return ResourceManager.GetString("SeatsTextMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрано {0} место.
        /// </summary>
        internal static string SeatsTextSingle {
            get {
                return ResourceManager.GetString("SeatsTextSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ряд {0}, Место {1}.
        /// </summary>
        internal static string SeatText {
            get {
                return ResourceManager.GetString("SeatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мест выбрано {0}.
        /// </summary>
        internal static string SelectedSeatsText {
            get {
                return ResourceManager.GetString("SelectedSeatsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список сеансов.
        /// </summary>
        internal static string ShowtimesListText {
            get {
                return ResourceManager.GetString("ShowtimesListText", resourceCulture);
            }
        }
    }
}
