SET NOCOUNT ON;

ALTER TABLE [Movie] ADD CONSTRAINT AgeLimitFK 
FOREIGN KEY (AgeLimitId) REFERENCES [AgeLimit] (Id)
	
ALTER TABLE [Showtime] ADD CONSTRAINT MovieShowtimeFK 
FOREIGN KEY (MovieId) REFERENCES [Movie] (Id) ON DELETE CASCADE

ALTER TABLE [Showtime] ADD CONSTRAINT AuditoriumShowtimeFK 
FOREIGN KEY (AuditoriumId) REFERENCES [Auditorium] (Id) ON DELETE CASCADE

ALTER TABLE [Ticket] ADD CONSTRAINT TicketShowtimeFK 
FOREIGN KEY (ShowtimeId) REFERENCES [Showtime] (Id) ON DELETE CASCADE

ALTER TABLE [MovieGenres] ADD CONSTRAINT MovieGenreFK 
FOREIGN KEY (MovieId) REFERENCES [Movie] (Id) ON DELETE CASCADE

ALTER TABLE [MovieGenres] ADD CONSTRAINT GenreMovieFK 
FOREIGN KEY (GenreId) REFERENCES [Genre] (Id) ON DELETE CASCADE