//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to создание.
        /// </summary>
        internal static string CreationText {
            get {
                return ResourceManager.GetString("CreationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удаление.
        /// </summary>
        internal static string DeletionText {
            get {
                return ResourceManager.GetString("DeletionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to редактирование.
        /// </summary>
        internal static string EditingText {
            get {
                return ResourceManager.GetString("EditingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to осталось {0} ч {1} мин.
        /// </summary>
        internal static string HoursLeftString {
            get {
                return ResourceManager.GetString("HoursLeftString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to осталось {0} мин.
        /// </summary>
        internal static string MinutesLeftString {
            get {
                return ResourceManager.GetString("MinutesLeftString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to осталось {0} минуты.
        /// </summary>
        internal static string MinutesTextCouple {
            get {
                return ResourceManager.GetString("MinutesTextCouple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to осталось {0} минут.
        /// </summary>
        internal static string MinutesTextMany {
            get {
                return ResourceManager.GetString("MinutesTextMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to осталась {0} минута.
        /// </summary>
        internal static string MinutesTextSingle {
            get {
                return ResourceManager.GetString("MinutesTextSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет сеансов.
        /// </summary>
        internal static string NoShowtimesTodayText {
            get {
                return ResourceManager.GetString("NoShowtimesTodayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ряд {0}, Место {1}.
        /// </summary>
        internal static string SeatText {
            get {
                return ResourceManager.GetString("SeatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D.
        /// </summary>
        internal static string ThreeDeeText {
            get {
                return ResourceManager.GetString("ThreeDeeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to завтра.
        /// </summary>
        internal static string TomorrowText {
            get {
                return ResourceManager.GetString("TomorrowText", resourceCulture);
            }
        }
    }
}
